[rules]
[rule.generic-api-key]
description = "Generic API Key"
regex = '''(?i)(api_key|apikey|access_token|auth_token|client_secret|consumer_key|consumer_secret|access_key|secret_key|token)[0-9]?[''"]?\s*[:=]\s*[''"]?([a-zA-Z0-9_=-]{20,})[''"]?'''
secretGroup = 2
disable = true

[rule.password-strength]
description = "Password Strength Validator"
regex = '''PASSWORD_STRENGTH'''
disable = true
